### ISSUE TITLE
Language bug

### ISSUE THREAD

**Issue by Aalexz** [afpineda/SimWheelESP32Config#2]
Traceback (most recent call last):
  File "__main__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "appstrings.py", line 266, in <module>
  File "appstrings.py", line 91, in _reset
  File "appstrings.py", line 82, in _decode_locale
appstrings.TranslatorException: 'English_United States' is not a valid locale string

**Comment by WallK** [comment]
> I got a jump on [release 2.1.0](https://github.com/afpineda/SimWheelESP32Config/releases/tag/2.1.0). Now, you may work around your issue by passing "en" as a command line argument. In windows:
> 
> ```shell
> ESP32SimWheel.exe en
> ```

Even while passing "en" as an argument -- I get `'English_World' is not a valid locale string`
If I set English (United States) in Windows settings -- I get `'English_United States' is not a valid locale string`
